issuer: https://token.actions.githubusercontent.com
subject_pattern: repo:super-smooth\/better-fg:ref:refs\/tags\/v.*
claim_pattern:
  job_workflow_ref: super-smooth/better-fg/.github/workflows/release.yml@.*
permissions:
  contents: write
