issuer: https://token.actions.githubusercontent.com
subject: repo:super-smooth/better-fg:ref:refs/heads/main
claim_pattern:
  job_workflow_ref: super-smooth/better-fg/.github/workflows/release.yml@.*
permissions:
  contents: write
